# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015, 2016, 2017 CERN.
#
# Invenio is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

addons:
  postgresql: 9.4

notifications:
  email: false

sudo: false

language: python

cache:
  - pip

services:
  - postgresql
  - rabbitmq
  - redis

env:
  - REQUIREMENTS=lowest ES_HOST=127.0.0.1 ES_VERSION=2.2.0 SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
  - REQUIREMENTS=release ES_HOST=127.0.0.1 ES_VERSION=2.2.0 SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
  - REQUIREMENTS=devel ES_HOST=127.0.0.1 ES_VERSION=2.2.0 SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"

python:
  - "2.7"
  - "3.5"

before_install:
  - "mkdir /tmp/elasticsearch"
  - "wget -O - https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1"
  - "/tmp/elasticsearch/bin/elasticsearch &"
  - "sleep 20"
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[all]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: lnielsen
  password:
    secure: "b+qTIIt8TMhs8/ZLiiHzvqYrNf2lpEuoxGmMSv8uY5Cq4/vLgnuUwEf9zz7m1bVSpkB63t+tqo7R0WfnnQFhySgJVPXyBJMkKqq6yZec7z0oUXDNjP0St/71LDPmEMI39mJnIPP68jSvkKCwFXHKL8O5S1DBdqyKq1iM5zWO8wikApRuW1NKep7j5sLo706w9af3wKZxEJDOHkAgb+l7TY9zpqlSAhIMDmTSxTYZ5OzV/w4nO+9htl0QGX4OgyLUF923RrbgWh+GxzfgwY3C/+LWpXQl/QWfWTRvaGKJnYEQc72LKzGu3t3eHzTWB1lJDWPE2vDpw4ZL8BGBSxK1771H16/8DiZcF0pgUt130PjFDiTg8xfiw7m0PrOzQRil8x0hgw9gUoLBzRE4EgO1Y+PSJfO/jjUDhX9x0ydjq8/21YK3p1GJJjt5V5ExRPDxethONNot6By6a9Ah5DZfDuQRCSZZ2bKjkKNHuin7K/CqqdtEulUSTuRzu5hxHiR8GpOVMmKXJtL6PRWLW5/2oBXcVtvCG8Qk9Qg5DaxJQ/iVczyCMoYf6hsyrR/I0KOmg/Sx0eUXFOH2vWbDpxm7YnJW9wohHhbyPyEvYYWE1QOj3NCEMoyBpiCZubvSL0weITkM2zTiQBVpoMsduPmxowkLVQ0s1IwyceixKBn07aI="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
    condition: $REQUIREMENTS = release
